---
- hosts: localhost
  connection: local
  vars:
    ssh_key: swarm
    swarm_num_nodes: 2
    swarm_security_group_name: swarm
    swarm_node_prefix: fufu
# This template name is specific to http://exoscale.ch, replace it
    swarm_template: Linux Ubuntu 15.10 64-bit 10G Disk (2016-03-29-19e783) 
    swarm_instance_type: Tiny

  roles:
    - common-exo
    - swarm-exo
