# internal
  - name: flannel etcd 2379
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ swarm_security_group_name }}"
     start_port: 2377
     end_port: 2377
     user_security_group: "{{ swarm_security_group_name }}"

  - name: libnetwork advertize 2376
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ swarm_security_group_name }}"
     start_port: 2376
     end_port: 2376
     user_security_group: "{{ swarm_security_group_name }}"

  - name: consul 8500
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ swarm_security_group_name }}"
     start_port: 8500
     end_port: 8500
     user_security_group: "{{ swarm_security_group_name }}"

  - name: flannel UDP 8472
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ swarm_security_group_name }}"
     start_port: 8472
     end_port: 8472
     protocol: udp
     user_security_group: "{{ swarm_security_group_name }}"

# external access

  - name: SSH for swarm
    local_action:
     module: cs_securitygroup_rule
     security_group: "{{ swarm_security_group_name }}"
     start_port: 22
     end_port: 22
